# Generated by Django 4.2 on 2024-05-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Лого')),
                ('hidden', models.BooleanField(default=False, verbose_name='Скрыта')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'db_table': 'companies',
            },
        ),
    ]
