# Generated by Django 4.2 on 2024-05-08 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos', verbose_name='Лого'),
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Должность')),
                ('description', models.TextField(verbose_name='Описание')),
                ('salary', models.CharField(default='Не указана', max_length=256, verbose_name='Заработная плата')),
                ('experience', models.CharField(choices=[('0_', 'Не имеет значения'), ('1_3', 'От 1 до 3 лет'), ('3_6', 'От 3 до 6 лет'), ('6_', 'От 6 лет')], max_length=64, verbose_name='Опыт работы')),
                ('employment', models.CharField(choices=[('full', 'Полная занятость'), ('part', 'Частичная занятость'), ('probation', 'Стажировка')], max_length=64, verbose_name='Тип занятости')),
                ('schedule', models.CharField(choices=[('full_day', 'Полный день'), ('shift', 'Сменный график'), ('flexible', 'Гибкий график'), ('remote', 'Удаленная работа'), ('fly_in_fly_out', 'Вахтовый метод')], max_length=64, verbose_name='График работы')),
                ('hidden', models.BooleanField(default=False, verbose_name='Скрыта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'db_table': 'vacancies',
            },
        ),
    ]
