# Generated by Django 4.2 on 2024-05-13 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_company_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-created_at'], 'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
    ]
